In [7]:
!pip install hmmlearn==0.2.2


     |████████████████████████████████| 146 kB 8.1 MB/s 
  Created wheel for hmmlearn: filename=hmmlearn-0.2.2-cp37-cp37m-linux_x86_64.whl size=329740 sha256=8beac5e052a367345dc00f9e85a965c7d682b8d3caf53fa8ef7862f9b7b652c8
  Stored in directory: /root/.cache/pip/wheels/66/1c/c5/d5572261032ef106444475a9921466143832e4943623234be4
Successfully built hmmlearn


In [2]:
#definisikan  Matriks Transisi (states)
states = ('Rainy', 'Sunny')
print(states)

('Rainy', 'Sunny')


In [3]:
#definisi Matriks Observasi / Matriks Emisi
observations = ('walks', 'shop', 'clean')
print(observations)

('walks', 'shop', 'clean')


In [4]:
#defisi Matrik Priority
start_probability = {'Rainy': 0.6, 'Sunny': 0.4}
print(start_probability)

{'Rainy': 0.6, 'Sunny': 0.4}


In [5]:
transition_probability = {
    'Rainy' : {'Rainy': 0.7, 'Sunny': 0.4},
    'Sunny' : {'Rainy': 0.6, 'Sunny': 0.3}
}
print(transition_probability)

{'Rainy': {'Rainy': 0.7, 'Sunny': 0.4}, 'Sunny': {'Rainy': 0.6, 'Sunny': 0.3}}


In [ ]:
emission_probability = {
    'Rainy' : {'walk': 0.1, 'shop': 0.5, 'clean': 0.4},
    'Sunny' : {'walk': 0.6, 'shop': 0.3, 'clean': 0.1}
}
print(emission_probability)

{'Rainy': {'walk': 0.1, 'shop': 0.5, 'clean': 0.4}, 'Sunny': {'walk': 0.6, 'shop': 0.3, 'clean': 0.1}}


In [8]:
# Library untuk HMM
# Cara install pip install hmmlearn==0.2.2

from hmmlearn import hmm
import numpy as np

In [9]:
model = hmm.MultinomialHMM(n_components=2)
model.startprob_ = np.array([0.6, 0.4])
model.transmat_ = np.array([[0.7, 0.3],
                            [0.4, 0.6]])
model.emissionprob_ = np.array([[0.1, 0.4, 0.5],
                                [0.6, 0.3, 0.1]])

In [13]:
# Given a known model what is the likelihood of sequence O happening?
# The probability of the first observation being “Walk” equals to the multiplication 
# of the initial state distribution and emission probability matrix.
# 0.6 x 0.1 + 0.4 x 0.6 = 0.30 (30%). 
# The log likelihood is provided from calling .score.
# catatan {'walk', 'shop','clean' }
# Kasus untuk initial state #
# contoh untuk observasi 'walk' 
# peluang dari model jika observasi adalah 'walk'
# 0.6 x 0.1 + 0.4 x 0.6 = 0.30 (30%)

import math 
math.exp(model.score(np.array([[0]])))

0.30000000000000004

In [ ]:
# contoh untuk observasi 'shop' 
# peluang dari model jika observasi adalah 'shop'
# 0.6 x 0.4 + 0.4 x 0.3 = (36%)

math.exp(model.score(np.array([[1]])))

0.36000000000000004

In [ ]:
# contoh untuk observasi 'clean' 
# peluang dari model jika observasi adalah 'clean'
# 0.6 x 0.5 + 0.4 x 0.1 = (34%)

math.exp(model.score(np.array([[2]])))

0.3400000000000001

In [ ]:
# contoh untuk observasi {'clean', 'clean'} 
# peluang dari model jika observasi {'clean', 'clean'} adalah

math.exp(model.score(np.array([[2,2]])))

0.1244

In [ ]:
#==== HMM decode dengan algoritma viterbi di dalamnya ======#

logprob, seq = model.decode(np.array([[1,2,0]]).transpose())
print(math.exp(logprob))
print(seq)

0.015120000000000003
[0 0 1]


In [14]:
logprob, seq = model.decode(np.array([[2,2,2]]).transpose())
print(math.exp(logprob))
print(seq)

0.03674999999999999
[0 0 0]


In [ ]:
#Hitung peluang dari model jika observasi {'clean', 'clean',’walk’, ‘walk’, ‘shop’} dari model yang ada
math.exp(model.score(np.array([[2,2,0,0,1]])))

0.004082395400000001

In [16]:
logprobx, seqx = model.decode(np.array([[2,2,0,0,1]]).transpose())
print(math.exp(logprobx))
print(seqx)

0.001224720000000001
[0 0 1 1 1]
